version: "3.9"

services:
  api:
    build: ./server
    container_name: workflow_api
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    expose:
      - "3000"

  web:
    build:
      context: ./client
    container_name: workflow_web
    restart: unless-stopped
    ports:
      - "8080:80"      # open http://localhost:8080
    depends_on:
      - api
