services:
  api:
    build: ./server
    container_name: workflow_api
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    expose:
      - "3000"

  web:
    build:
      context: ./client
    container_name: workflow_web
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - api

  caddy:
    image: caddy:alpine
    container_name: workflow_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file: .env     # <-- lets {$ROOT_DOMAIN} and {$PORT} work in Caddyfile
    depends_on:
      - web
      - api



  
volumes:
  caddy_data:
  caddy_config:

